baseURL = "Domain" # Your Domain
title = "SiteName" # Your Title
languageCode = "LocaleInfo" # Language ID 
hasCJKLanguage = true # Check to Count Chinese Characters
theme = "ThemeID" # Your Theme Folder Name
paginate = PagesNumber # Pages to show on homepage
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "GAID" # Google Analytics ID
preserveTaxonomyNames = true
[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true
[Permalinks]
 posts = "/:year/:filename/"
[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
[params]
    since = SINCEYEAR
    author = "AUTHORNAME"                          # Author's name
    avatar = "AVATARPIC"           # Author's avatar
    subtitle = "SLOGAN"                  # Subtitle
    home_mode = "post"
    license= 'All my articles are authorized using <a rel="license" href="LICENSEURL" target="_blank">[LICENSENAME]</a>'
[params.social]
    GitHub = "GHID"
    Twitter = "TTID"
    Email   = "EMAD"
    Instagram = "INSID"
    Wechat = "QRCODEURL"  # Wechat QRcode image
    Facebook = "FBID"
    Telegram = "TGID"
